# DISABLED: Workflow disabled in fork to prevent CI runs on upstream PRs
name: Backport
on:
  pull_request_target:
    types: [closed]
  workflow_dispatch:
    inputs:
      disabled:
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v6
        with:
          repository: "frappe/backport"
          path: ./actions
          ref: develop
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run backport
        uses: ./actions/backport
        with:
          token: ${{secrets.RELEASE_TOKEN}}
          labelsToAdd: "backport"
          title: "{{originalTitle}}"
