# DISABLED: Workflow disabled in fork to prevent CI runs on upstream PRs
name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [closed]
  workflow_dispatch:
    inputs:
      disabled:
        type: boolean
        default: true

permissions:
  issues: write
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
