# DISABLED: Workflow disabled in fork to prevent CI runs on upstream PRs
# Tests are skipped for these files but github doesn't allow "passing" hence this is required.

name: Skipped Patch Test

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      disabled:
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    name: Patch Test

    steps:
      - name: Pass skipped tests unconditionally
        run: "echo Skipped"
